environment:
  PATH: C:\\Python37;C:\\Python37\Scripts;C:\Users\appveyor\AppData\Roaming\Python\Python37\Scripts;%PATH%
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

configuration: Release

install:
  - python -m pip install conan PyYAML
  - python -m conans.conan user

build_script:
  - mkdir build && cd build
  - python -m conans.conan install ..
  - python -m conans.conan build ..
  - ctest . -C %CONFIGURATION% --verbose
  - cpack -C %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER% && python create_source_tarball.py
  - 7z x -y naive-tsearch-*.tar.gz && 7z x -y naive-tsearch-*.tar && del naive-tsearch-*.tar && del *.tar.* && cd naive-tsearch-*
  - mkdir build && cd build
  - python -m conans.conan install ..
  - python -m conans.conan build ..
