language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: clang
    osx_image: xcode11.3

script:
  - mkdir build && cd build
  - cmake .. -DNAIVE_TSEARCH_INSTALL=ON -DNAIVE_TSEARCH_TESTS=ON -DCMAKE_INSTALL_PREFIX=prefix
  - cmake --build .
  - cmake --build . --target install
  - cmake --build . --target package_source
