language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
  - os: linux
    dist: bionic
    compiler: clang
  - os: osx
    compiler: clang
    osx_image: xcode11.3

before_install:
  - .ci/install.sh

script:
  - mkdir build && cd build
  - cmake .. -DNAIVE_TSEARCH_INSTALL=ON -DNAIVE_TSEARCH_TESTS=ON -DCMAKE_INSTALL_PREFIX=prefix
  - cmake --build .
  - cmake --build . --target install
  - cmake --build . --target package_source
  - ctest . --verbose
