language: cpp

dist: bionic

osx_image: xcode11.3

os:
  - linux
  - osx

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

compiler:
  - gcc
  - clang

before_install:
  - .ci/install.sh

script:
  - mkdir build && cd build
  - cmake .. -DNAIVE_TSEARCH_INSTALL=ON -DNAIVE_TSEARCH_TESTS=ON -DCMAKE_INSTALL_PREFIX=prefix
  - cmake --build .
  - cmake --build . --target install
  - cmake --build . --target package_source
  - ctest . --verbose
  - cpack
  - cd "$TRAVIS_BUILD_DIR" && python3 create_source_tarball.py
  - tar xvf naive-tsearch-*.tar.gz && rm *.tar.* && cd naive-tsearch-*
  - mkdir build && cd build
  - cmake .. -DNAIVE_TSEARCH_INSTALL=ON -DNAIVE_TSEARCH_TESTS=ON -DCMAKE_INSTALL_PREFIX=prefix
  - cmake --build .
